Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,8 +25,16 @@ jobs:
           echo "Starting deployment... 3"
           cd C:\Danil\MyApps\Apps\Defender.IdentityService\
           git pull origin main
+          if [ $? -ne 0 ]; then
+            echo "Git pull failed"
+            exit 1
+          fi
           echo "Code pulled successfully"
           cd ../..
           echo "Starting Docker build..."
           docker-compose -f dev-core-docker-compose.yml -p dev up -d --build dev-identity-service
+          if [ $? -ne 0 ]; then
+            echo "Docker build failed"
+            exit 1
+          fi
           echo "Deployment completed."
